Repository wecode-bootcamp-korea/24-1st-LaFesta-frontend, pull requests merged in 2021-09, with the labels that each got.

#5 [24기 이송현]Fix: 공통 푸터 컴포넌트 수정 리뷰 요청
  src/components/Footer/Footer.scss
Labels: Status: Accepted

#2 [24기 정도영] Fix & Add: 리뷰내용 반영 리팩토링, 스타일(핏)별 제품리스트 재배치 기능 추가
  public/data/productListData-doyoung.json
  public/images/images-doyoung/categoryIntro.avif
  public/index.html
  src/components/Footer/Footer.js
  src/font/metropolis.light.otf
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
  src/pages/ProductList/productListComponent/Product.js
  src/pages/ProductList/productListComponent/product.scss
  src/styles/common.scss
Labels: Status: Accepted

#9 [24기 정도영] Fix: ProductList 페이지 새 branch 생성 및 리뷰 내용 반영
  public/data/productListData-doyoung.json
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
  src/pages/ProductList/productListComponent/Product.js
  src/pages/ProductList/productListComponent/product.scss
Labels: Status: 리뷰 요청

#4 [24기 이송현] Add: 공통 네비게이션 컴포넌트 리뷰 요청
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/styles/common.scss
  src/styles/reset.scss
Labels: Status: 리뷰 요청, Status: 수정 요청

#14 [24기 이송현] Modify : 공통 푸터 컴포넌트
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
Labels: Status: Accepted

#8 [24기 정도영] Fix: 리뷰내용 반영 리팩토링
  public/data/productListData-doyoung.json
  src/Routes.js
  src/font/metropolis.light.otf
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
  src/pages/ProductList/productListComponent/Product.js
  src/pages/ProductList/productListComponent/ProductFilter.js
  src/pages/ProductList/productListComponent/ProductFilter.scss
  src/pages/ProductList/productListComponent/product.scss
Labels: Status: 리뷰 요청

#12 [24기 이송현] Modify: 네비게이션 컴포넌트 리뷰 반영 카테고리 아이템 세분화
  src/components/Nav/Category/Category.js
  src/components/Nav/Category/Category.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/PopUp/PopUp.js
  src/components/PopUp/PopUp.scss
  src/styles/common.scss
Labels: Status: 리뷰 요청

#13 [24기 최파란별] Refactor- checkList state 값 배열-> 객체,배열로 변경
  src/Routes.js
  src/pages/SignUp/Check.jsx
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
  src/pages/SignUp/SignUpCertification.jsx
  src/pages/SignUp/SignUpCertification.scss
  src/pages/SignUp/SignUpTermsUse.jsx
  src/pages/SignUp/SignUpTermsUse.scss
  src/pages/SignUp/SignUpUserInfo.jsx
  src/pages/SignUp/SignUpUserInfo.scss
Labels: Status: 리뷰 요청

#17 [24기 최파란별] Add: 로그인성공시 토큰저장 구현
  src/pages/LogIn/Login.js
Labels: Status: 리뷰 요청

#7 [24기 이송현] Add: 메인 페이지 컴포넌트 리뷰 요청
  public/data/mainData-songhyun.json
  public/data/productListData-doyoung.json
  src/Routes.js
  src/pages/Error/NotFound.js
  src/pages/Error/NotFound.scss
  src/pages/MainPage/MainItem/MainItem.js
  src/pages/MainPage/MainItem/MainItem.scss
  src/pages/MainPage/MainPage.js
  src/pages/MainPage/MainPage.scss
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductListComponent/Product.js
  src/pages/ProductList/ProductListComponent/Product.scss
  src/pages/ProductList/ProductListComponent/ProductFilter.js
  src/pages/ProductList/ProductListComponent/ProductFilter.scss
Labels: Status: 리뷰 요청

#16 [24기 이송현] Modify: PopUP 컴포넌트 리뷰 요청
  src/Routes.js
  src/components/Form/Form.js
  src/components/Form/Form.scss
  src/components/Nav/Category/Category.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/PopUp/PopUp.js
  src/components/PopUp/PopUp.scss
  src/pages/LogIn/Login.js
  src/pages/ProductList/ProductListComponent/Product.scss
  src/pages/SignUp/SignUpUserInfo.jsx
Labels: Status: 리뷰 요청

#15 [24기 정도영] Add: 장바구니 레이아웃 1차 완료
  public/data/cartListData-doyoung.json
  src/components/Nav/Category/Category.scss
  src/components/Nav/Nav.scss
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/CartComponent/CartList.js
  src/pages/Cart/CartComponent/CartList.scss
  src/pages/Cart/CartComponent/CheckedCartList.js
  src/pages/Cart/CartComponent/CheckedCartList.scss
  src/pages/Cart/CartComponent/CheckedPriceInfo.js
  src/pages/Cart/CartComponent/CheckedPriceInfo.scss
  src/pages/Cart/CartComponent/PriceInfo.js
  src/pages/Cart/CartComponent/PriceInfo.scss
  src/pages/Cart/CartPage/Delivery.js
  src/pages/Cart/CartPage/Delivery.scss
  src/pages/Cart/CartPage/Payment.js
  src/pages/Cart/CartPage/Payment.scss
  src/pages/Cart/CartPage/ShoppingBag.js
  src/pages/Cart/CartPage/ShoppingBag.scss
  src/pages/ProductList/ProductList.js
Labels: Status: 수정 요청

#11 [24기 최파란별] Refactor- 중복 코드 제거 및 코드 단축화
  .vscode/settings.json
  public/data/productData.json
  public/index.html
  src/Routes.js
  src/components/Nav/Nav.scss
  src/config.js
  src/pages/LogIn/Login.js
  src/pages/ProductDetail/CARD_DATA.js
  src/pages/ProductDetail/ProductBonus.js
  src/pages/ProductDetail/ProductBonus.scss
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductDetail/ProductPhoto.js
  src/pages/ProductDetail/ProductSize.js
  src/pages/ProductDetail/ProductSize.scss
  src/pages/ProductDetail/ShoppingBag.js
  src/pages/ProductDetail/ShoppingBag.scss
Labels: Status: 리뷰 요청

#19 [24기 이송현] Add : 네비게이션 로그아웃 기능 추가 리뷰 요청
  src/components/Nav/Nav.js
  src/components/PopUp/PopUp.js
Labels: Status: 리뷰 요청

#18 [24기 정도영] Fix: 리팩토링 완료
  public/data/cartListData-doyoung.json
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/PopUp/PopUp.scss
  src/config.js
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/CartComponent/CartList.js
  src/pages/Cart/CartComponent/CartList.scss
  src/pages/Cart/CartComponent/CheckedCartList.js
  src/pages/Cart/CartComponent/CheckedPriceInfo.js
  src/pages/Cart/CartComponent/PriceInfo.js
  src/pages/Cart/CartPage/Delivery.js
  src/pages/Cart/CartPage/Delivery.scss
  src/pages/Cart/CartPage/Payment.js
  src/pages/Cart/CartPage/ShoppingBag.js
  src/pages/Cart/CartPage/ShoppingBag.scss
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
  src/pages/ProductList/ProductListComponent/Product.js
  src/pages/ProductList/ProductListComponent/ProductFilter.js
  src/pages/ProductList/ProductListComponent/ProductFilter.scss
Labels: Status: 리뷰 요청
